<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-02-24 at 05:11:54.
 */
class SampleTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Sample
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Sample;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert 10,-10 == 0.
     *
     * @covers Sample::add
     */
    public function testAdd()
    {
        $this->assertEquals(
            0,
            Sample::add(10,-10)
        );
    }

    /**
     * Generated from @assert -9223372036854775808,0 == -9223372036854775808.
     *
     * @covers Sample::add
     */
    public function testAdd2()
    {
        $this->assertEquals(
            -9223372036854775808,
            Sample::add(-9223372036854775808,0)
        );
    }

    /**
     * Generated from @assert -10,0 == -10.
     *
     * @covers Sample::add
     */
    public function testAdd3()
    {
        $this->assertEquals(
            -10,
            Sample::add(-10,0)
        );
    }
}
